# Generated by Django 6.1.1 on 2026-09-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('isbn', models.CharField(max_length=13, unique=True)),
                ('data_publicacao', models.DateField()),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
